version: '3.8'

services:
  mongo_db:
    image: mongo
    ports:
      - "0.0.0.0:3456:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes: 
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./mongo_data:/data/db
    container_name: hillandback-dev-mongo  

  mongo_db_test:
    image: mongo
    ports:
      - "0.0.0.0:3457:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_test_database
    volumes: 
      - ./mongo/mongotest-init.js:/docker-entrypoint-initdb.d/mongotest-init.js
    container_name: hillandback-dev-test-mongo   

volumes:
  mongo_data:










    
