name: hilland_e2e CI

on:
  push:
    branches: [ "main" ]
env:
  NODE_ENV: test
  TEST_MONGODB_URI: mongodb://localhost:27017/testing
  TEST_S3_MOCK_ENDPOINT: http://localhost:4566
  AWS_REGION: eu-central-1
  AWS_S3_BUCKET: hillandwebimgs
  SECRET: actions
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} 
  
jobs:
  end_to_end_test_scheduled:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        mongodb-version: ['6.0']

        
    steps:
          - name: Checkout code
            uses: actions/checkout@v3
            
          - name: install frontend npm dependencies with caching
            uses: bahmutov/npm-install@v1
            with:
              working-directory: ./hilland_front
              
          - name: run lint 
            working-directory: ./hilland_front
            run: |
              npm run lint
              
          - name: Run test front  
            working-directory: ./hilland_front
            run: 
                npm run test

          - name: install backend npm dependencies with caching
            uses: bahmutov/npm-install@v1
            with:
              working-directory: ./hilland_backend
              
          - name: Start MongoDB
            uses: supercharge/mongodb-github-action@1.8.0
            with:
              mongodb-version: ${{ matrix.mongodb-version }}   
          - name: Start LocalStack
            uses: LocalStack/setup-localstack@v0.1.2
            with:
              image-tag: 'latest'
              configuration: DEBUG=1
              install-awslocal: 'true'
              use-pro: false
            env:
            # Set the AWS credentials for LocalStack
              AWS_SECRET_ACCESS_KEY: test
              AWS_ACCESS_KEY_ID: test
          - name: Run Tests against LocalStack
            run: |
              awslocal s3 mb s3://test
              awslocal s3 ls
              echo "Test Execution complete!"    

          - name: build client and start server
            working-directory: ./hilland_backend
            run: |
              npm run start:full:test &

          - name: Install Cypress and run tests
            uses: cypress-io/github-action@v5
            with:
              browser: chrome
              working-directory: ./hilland_front
              install: false
              config: pageLoadTimeout=10000,baseUrl=http://localhost:3001
              wait-on: 'http://localhost:3001'
              wait-on-timeout: 180

          - uses: actions/upload-artifact@v3
            if: failure()
            with:
              name: cypress-screenshots
              path: ./client/cypress/screenshots
          
          - uses: actions/upload-artifact@v3
            if: always()
            with:
              name: cypress-videos
              path: ./client/cypress/videos    
              
  
