name: hilland_backend CI

on:
  pull_request: 
    branches: [main] 
    types: [opened, synchronize]   
env:
  NODE_ENV: test
  TEST_MONGODB_URI: mongodb://localhost:27017/testing
  TEST_S3_MOCK_ENDPOINT: http://localhost:4566
  AWS_REGION: eu-central-1
  AWS_S3_BUCKET: hillandwebimgs
  SECRET: actions
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} 
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: hilland_backend
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        mongodb-version: ['4.2', '4.4', '5.0', '6.0']
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './hilland_backend/package-lock.json'
    - name: Clear npm Cache
      run: npm cache clean --force    
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.8.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}   
    - name: Start LocalStack
      run: |
        pip install localstack awscli-local[ver1] # install LocalStack cli and awslocal
        docker pull localstack/localstack         # Make sure to pull the latest version of the image

        # Start LocalStack and wait for it to become ready
        localstack start --docker -d

        # Wait for LocalStack to be ready (you may need to adjust the timeout)
        echo "Waiting for LocalStack startup..."
        localstack logs -f  # You can use this command to see the logs and adjust the timeout accordingly
        localstack wait --check-cmd "localstack info" -t 300

        echo "Startup complete"
      env:
        # Set the AWS credentials for LocalStack
        AWS_SECRET_ACCESS_KEY: test
        AWS_ACCESS_KEY_ID: test
    - name: Run Tests against LocalStack
      run: |
          awslocal s3 mb s3://test
          awslocal s3 ls
          echo "Test Execution complete!"     
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run lint
    - run: npm test
  
    
