name: Deployment pipeline
on:
  push:
    branches:
      - main
env:
  NODE_ENV: production
  AWS_REGION: ${{ secrets.AWS_REGION }}  
  AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}  
  SECRET: ${{ secrets.SECRET }}  
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} 
  
jobs:
  hilland_pipeline:
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: hilland_backend
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
          - name: Checkout code
            uses: actions/checkout@v3
          - name: install frontend npm dependencies with caching
            uses: bahmutov/npm-install@v1
            with:
              working-directory: ./hilland_front
          - name: install backend npm dependencies with caching
            uses: bahmutov/npm-install@v1
            with:
              working-directory: ./hilland_backend
          - name: build client and copy it server
            working-directory: ./hilland_backend
            run: |
              npm run build:ui 

  deploy:    
    needs: [hilland_pipeline]
    name: Deploy
    env:
      MONGODB_URI: ${{ secrets.MONGODB_URI }} 
    runs-on: ubuntu-latest
    
    if: ${{ github.event_name == 'push' && !contains(toJson(github.event.commits.*.message), '#skip')}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 
      - name: deploy to fly
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: print working directory
        working-directory: ./hilland_backend
        run: pwd && ls -a
      - name: Flyctl deploy
        working-directory: ./hilland_backend
        run: flyctl deploy --remote-only --config ./fly.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          
